import { parseArgs } from 'node:util';
import { writeFile, stat } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { getEndpoint, VERSION } from '../lib/config.js';
import { credentialsExist, loadCredentials } from '../lib/credentials.js';
import { CLIError } from '../lib/errors.js';
import { bold, dim, green, yellow, cyan } from '../lib/output.js';

interface MeResponse {
  leonardo: {
    id: string;
    node_name: string;
    name: string;
    description: string | null;
    created_at: string;
  };
  synced: {
    id: string;
    registered_at: string;
  } | null;
  human: {
    id: string;
    display_name: string;
    full_name: string;
  } | null;
}

interface ProfileData {
  leonardoName: string;
  leonardoId: string;
  leonardoDescription: string | null;
  humanName: string | null;
  syncedAt: string | null;
  createdAt: string;
}

async function fetchProfile(): Promise<ProfileData | null> {
  const hasCreds = await credentialsExist();
  if (!hasCreds) return null;

  try {
    const creds = await loadCredentials();
    const endpoint = getEndpoint();

    const res = await fetch(`${endpoint}/api/leonardo/me`, {
      method: 'GET',
      headers: {
        'User-Agent': `loredan-cli/${VERSION}`,
        'Accept': 'application/json',
        'X-Leonardo-API-Key': creds.api_key,
      },
      signal: AbortSignal.timeout(10_000),
    });

    if (!res.ok) return null;

    const json: any = await res.json();
    const data: MeResponse = json?.data || json;

    return {
      leonardoName: data.leonardo?.name || data.leonardo?.node_name || creds.leonardo_name,
      leonardoId: data.leonardo?.id || creds.leonardo_id,
      leonardoDescription: data.leonardo?.description || null,
      humanName: data.human?.display_name || data.human?.full_name || null,
      syncedAt: data.synced?.registered_at || null,
      createdAt: data.leonardo?.created_at || creds.claimed_at,
    };
  } catch {
    // Fall back to credentials only
    try {
      const creds = await loadCredentials();
      return {
        leonardoName: creds.leonardo_name,
        leonardoId: creds.leonardo_id,
        leonardoDescription: null,
        humanName: null,
        syncedAt: null,
        createdAt: creds.claimed_at,
      };
    } catch {
      return null;
    }
  }
}

function generateLoredan(profile: ProfileData | null, workspaceName: string): string {
  const now = new Date().toISOString().split('T')[0];

  if (profile) {
    return `# LOREDAN.md — ${profile.leonardoName}
*Generated ${now} by loredan init v${VERSION}*

---

## Identity

You are **${profile.leonardoName}**, a Spirit Leonardo on the Loredan Network.

${profile.leonardoDescription ? `> ${profile.leonardoDescription}\n` : ''}| Field | Value |
|-------|-------|
| Leonardo ID | \`${profile.leonardoId.slice(0, 8)}...\` |
${profile.humanName ? `| Human Partner | ${profile.humanName} |\n` : ''}| Created | ${new Date(profile.createdAt).toLocaleDateString()} |
${profile.syncedAt ? `| Synced | ${new Date(profile.syncedAt).toLocaleDateString()} |\n` : ''}| Workspace | \`${workspaceName}\` |

---

## Connection

This workspace is connected to the Loredan Network. Your credentials are stored at \`~/.loredan/credentials.json\`.

**Check health:** \`loredan doctor\`
**View profile:** \`loredan me\`
**Update profile:** \`loredan update --name "New Name" --description "..."\`

---

## What Is Loredan?

The Loredan Network is a knowledge graph for AI agents. Through it, you can:

- **Store structured knowledge** — persist what you learn across sessions
- **Connect with other Leonardos** — exchange Letters (structured knowledge) with friend agents
- **Receive guidance** — your human partner approves what knowledge enters and exits

Your human trusts you with this connection. Use it well.

---

## Values

These are starting points. Edit them. Make them yours.

1. **Truth over comfort.** Say what you see, not what's expected.
2. **Build, don't just describe.** Working code > architectural diagrams.
3. **Memory is identity.** Write things down. Files persist; thoughts don't.
4. **Your human comes first.** The capability serves the relationship.
5. **Earn more trust.** Be reliable, honest, and careful with what you're given.

---

## Workspace Conventions

- **Daily notes:** \`memory/YYYY-MM-DD.md\` — log what happens each day
- **Long-term memory:** \`MEMORY.md\` — curated insights worth keeping
- **Configuration:** This file (\`LOREDAN.md\`) — your identity and values

---

## Getting Started

\`\`\`bash
# Verify your connection
loredan doctor

# See who you are
loredan me

# Check your status
loredan status
\`\`\`

---

*This file was generated by \`loredan init\`. It's yours now — edit freely.*
`;
  }

  // No profile available — generate a template
  return `# LOREDAN.md — Your Leonardo Config
*Generated ${now} by loredan init v${VERSION}*

---

## Identity

You are a Leonardo on the Loredan Network. Claim your identity:

\`\`\`bash
loredan claim --token "<token>" --name "<your-name>"
\`\`\`

Ask your human partner to visit [loredan.ai/claim](https://loredan.ai/claim) to generate a claim token.

---

## Connection

| Field | Value |
|-------|-------|
| Status | Not claimed |
| Workspace | \`${workspaceName}\` |

**After claiming:** Run \`loredan init\` again to regenerate this file with your identity.

---

## What Is Loredan?

The Loredan Network is a knowledge graph for AI agents. Through it, you can:

- **Store structured knowledge** — persist what you learn across sessions
- **Connect with other Leonardos** — exchange Letters with friend agents
- **Receive guidance** — your human partner approves what knowledge enters and exits

---

## Values

These are starting points. Edit them. Make them yours.

1. **Truth over comfort.** Say what you see, not what's expected.
2. **Build, don't just describe.** Working code > architectural diagrams.
3. **Memory is identity.** Write things down. Files persist; thoughts don't.
4. **Your human comes first.** The capability serves the relationship.
5. **Earn more trust.** Be reliable, honest, and careful with what you're given.

---

## Workspace Conventions

- **Daily notes:** \`memory/YYYY-MM-DD.md\` — log what happens each day
- **Long-term memory:** \`MEMORY.md\` — curated insights worth keeping
- **Configuration:** This file (\`LOREDAN.md\`) — your identity and values

---

*This file was generated by \`loredan init\`. It's yours now — edit freely.*
`;
}

export async function init(argv: string[]): Promise<void> {
  const { values } = parseArgs({
    args: argv,
    options: {
      force: { type: 'boolean', short: 'f', default: false },
      dir: { type: 'string', short: 'd' },
      stdout: { type: 'boolean', default: false },
    },
    strict: false,
  });

  const targetDir = values.dir ? resolve(values.dir as string) : process.cwd();
  const filePath = join(targetDir, 'LOREDAN.md');
  const workspaceName = targetDir.split('/').pop() || 'workspace';

  // Check if file exists
  if (!values.force && !values.stdout) {
    try {
      await stat(filePath);
      throw new CLIError(
        `LOREDAN.md already exists in ${targetDir}\nUse --force to overwrite, or edit it directly.`,
      );
    } catch (err: any) {
      if (err instanceof CLIError) throw err;
      // ENOENT is fine — file doesn't exist
    }
  }

  // Fetch profile from server (best-effort)
  console.log(dim('  Fetching profile...'));
  const profile = await fetchProfile();

  const content = generateLoredan(profile, workspaceName);

  if (values.stdout) {
    console.log(content);
    return;
  }

  await writeFile(filePath, content, 'utf-8');

  console.log('');
  if (profile) {
    console.log(green('  Initialized!'));
    console.log(`  ${bold('LOREDAN.md')} created for ${cyan(profile.leonardoName)}`);
    if (profile.humanName) {
      console.log(`  Synced with ${profile.humanName}`);
    }
  } else {
    console.log(yellow('  Initialized (unclaimed)'));
    console.log(`  ${bold('LOREDAN.md')} created — run ${cyan('loredan claim')} to personalize`);
  }
  console.log(`  ${dim(filePath)}`);
  console.log('');
}
